config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'talks' => 'talks#index', as: :talks
  get 'talks/:id' => 'talks#show', as: :talk

  get 'sitemap' => 'sitemap#index', format: :xml, as: :sitemap

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article
  attr_accessor :content, :created_at, :excerpt, :image_url, :slug, :title

  def initialize(title, slug, content, created_at = Time.now, excerpt = '', image_url = nil)
    self.content = content
    self.created_at = created_at
    self.excerpt = excerpt
    self.image_url = image_url
    self.slug = slug
    self.title = title
  end

  def feature_image_url
    if image_url.start_with?("//")
      return "https:#{image_url}"
    end

    return image_url
  end

  def to_json
    {
      content: content,
      created_at: created_at,
      excerpt: excerpt,
      image_url: image_url,
      slug: slug,
      title: title
    }.to_json
  end
end

app/models/talk.rb
class Talk
  attr_accessor :content, :created_at, :embed, :slug, :title

  def initialize(title, slug, embed, content, created_at = Time.now)
    self.content = content
    self.created_at = created_at
    self.embed = embed
    self.slug = slug
    self.title = title
  end

  def poster_url
    matches = /youtube.com\/embed\/([A-Za-z0-9]+)/.match(self.embed)
    return 'https://carepharmaceuticals.com.au/wp-content/uploads/sites/19/2018/02/placeholder-600x400.png' if matches[1].nil?

    return "https://img.youtube.com/vi/#{matches[1]}/0.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = ContentService.instance.list_articles.sort { |a, b| b.created_at <=> a.created_at }
        @featured_article = @articles.shift
    end

    def show
        # The id is really the slug
        slug = params[:id]
        @article = ContentService.instance.find_article(slug)
        @title = @article.title

        renderer = Redcarpet::Markdown.new(CustomRender, fenced_code_blocks: true)

        doc = Nokogiri::HTML::DocumentFragment.parse(renderer.render(@article.content))

        @articleContent = doc.to_s
    end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
    @articles = ContentService.instance.list_articles.sort { |a, b| b.created_at <=> a.created_at }
    @talks = ContentService.instance.list_talks.sort { |a, b| b.created_at <=> a.created_at }
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController

  def index
      @talks = ContentService.instance.list_talks.sort { |a, b| b.created_at <=> a.created_at }
  end

  def show
      # The id is really the slug
      slug = params[:id]
      @talk = ContentService.instance.find_talk(slug)
      @title = @talk.title
  end
end

app/helpers/application_helper.rb
class CustomRender < Redcarpet::Render::HTML
    def image(link, title, alt_text)
        %(<img alt="#{alt_text}" class="lazy" data-src="#{link}" title="#{title}" src="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==" />)
    end
end

module ApplicationHelper
    def markdown(text)
        return '' if text.nil?

        renderer = Redcarpet::Markdown.new(CustomRender, fenced_code_blocks: true)
        doc = Nokogiri::HTML::DocumentFragment.parse(renderer.render(text))
        doc.css('code[@class]').each do |code|
            div = CodeRay.scan(code.text.rstrip, code[:class].to_sym).div
            code = code.replace(div)
            code.first.parent.swap(code.first)
        end
        return doc.to_s
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<article class="featured-article">
    <%= image_tag @featured_article.image_url, alt: @featured_article.title, class: 'featured-article__image'  %>
    <div class="featured-article__info">
        <h2>
            <%= link_to @featured_article.title, article_path(@featured_article.slug), class: 'featured-article__title' %>
        </h2>
        <div class="featured-article__excerpt">
            <%= raw markdown @featured_article.excerpt %>
        </div>
    </div>
</article>

<div class="article-list">
    <% @articles.each do |article| %>

        <article class="article-item">
            <div class="article-item__image" style="background-image: url('<%= article.image_url %>')">
            </div>
            <div class="article-item__info">
                <h2>
                    <%= link_to article.title, article_path(article.slug), class: 'article-item__title' %>
                </h2>
                <div class="article-item__excerpt">
                    <%= raw markdown article.excerpt %>
                </div>
            </div>
        </article>

    <% end %>
</div>

app/views/articles/show.html.erb
<% content_for :custom_meta_tags do %>
  <meta name="description" content="<%= @article.excerpt %>" />

  <meta property="og:title" content="<%= @article.title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:description" content="<%= @article.excerpt %>" />
  <meta property="og:image" content="<%= @article.image_url %>" />

  <meta property="twitter:title" content="<%= @article.title %>" />
  <meta property="twitter:card" content="summary" />
  <meta property="twitter:description" content="<%= @article.excerpt %>" />
  <meta property="twitter:image" content="<%= @article.image_url %>" />
<% end %>

<% content_for :structured_data do %>
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Article",
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": "<%= request.original_url %>"
        },
        "headline": "<%= @article.title %>",
        "image": [
            "<%= @article.feature_image_url %>"
        ],
        "datePublished": "<%= @article.created_at.iso8601 %>",
        "dateModified": "<%= @article.created_at.iso8601 %>",
        "author": {
            "@type": "Person",
            "name": "Christoffer Artmann"
        },
        "publisher": {
            "@type": "Organization",
            "name": "All things GameDev",
            "logo": {
            "@type": "ImageObject",
            "url": "https://allthingsgamedev.com/favicon-96x96.png"
            }
        },
        "description": "<%= @article.excerpt %>"
    }
    </script>
<% end %>

<article class="article">
    <h1 class="article__title">
        <%= @article.title %>
    </h1>
    <div class="article__meta">
        <p><%= @article.created_at.strftime("%B %d, %Y") %></p>
    </div>
    <div class="article__container">
        <div class="article__body">
            <%= image_tag @article.image_url, alt: @article.title, class: 'article__image' %>

            <div class="article__content">
                <%= raw @articleContent %>
            </div>

            <div>
                <%= render "shared/disqus" %>
            </div>
        </div>
        <div class="article__sidebar">

        </div>
    </div>
</article>

<script>
    (function() {
        hljs.initHighlightingOnLoad();
    })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Open+Sans:400,700&family=Source+Code+Pro" rel="stylesheet">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.0/styles/gruvbox-dark.min.css">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <% unless yield(:custom_meta_tags).blank? %>
        <%= yield :custom_meta_tags %>
    <% end %>

    <% unless yield(:structured_data).blank? %>
        <%= yield :structured_data %>
    <% end %>

    <title>
      <%= @title ? @title : "All Things GameDev" %>
    </title>

    <script data-ad-client="ca-pub-7586045516328295" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js" integrity="sha512-TDKKr+IvoqZnPzc3l35hdjpHD0m+b2EC2SrLEgKDRWpxf2rFCxemkgvJ5kfU48ip+Y+m2XVKyOCD85ybtlZDmw==" crossorigin="anonymous"></script>

  </head>
  <body>

    <nav>
      <i class="material-icons mobile-menu-button">menu</i>
      <%= link_to 'All Things GameDev', :root, class: 'brand' %>
      <div class="nav__links">
        <%= link_to 'Home', :root, class: 'nav__link' %>
        <%= link_to 'Talks', :talks, class: 'nav__link' %>
      </div>

      <div class="mobile-menu">
        <%= link_to 'Home', :root, class: 'nav__link' %>
        <%= link_to 'Talks', :talks, class: 'nav__link' %>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <%= link_to('https://www.contentful.com/', class: 'contentful-logo') do %>
        <%= image_tag('contentful.png') %>
      <% end %>
    </footer>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= ENV['GA_TOKEN'] || '' %>', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>

<script>
  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');

    s.src = 'https://allthingsgamedev.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());

    (d.head || d.body).appendChild(s);
  })();
</script>

<noscript>
  Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>

app/views/sitemap/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
      <loc><%= root_url %></loc>
      <lastmod><%= @articles.first.created_at.strftime("%Y-%m-%d") %></lastmod>
      <changefreq>monthly</changefreq>
      <priority>1</priority>
    </url>

    <% @articles.each do |article| %>
      <url>
        <loc><%= article_url(article.slug) %></loc>
        <lastmod><%= article.created_at.strftime("%Y-%m-%d") %></lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
      </url>
     <% end %>

      <% @talks.each do |talk| %>
      <url>
        <loc><%= talk_url(talk.slug) %></loc>
        <lastmod><%= talk.created_at.strftime("%Y-%m-%d") %></lastmod>
        <changefreq>monthly</changefreq>
        <priority>1</priority>
      </url>
     <% end %>
    
  </urlset>

app/views/talks/index.html.erb
<div class="talks-list">
  <% @talks.each do |talk| %>

    <%= link_to talk_path(talk.slug), class: 'talk-item' do %>
      <div class="talk-item__image" style="background-image: url('<%= talk.poster_url %>')">
      </div>
      <div class="talk-item__info">
        <h2 class="talk-item__title"><%= talk.title %></h2>
      </div>
    <% end %>

  <% end %>
</div>

app/views/talks/show.html.erb
<% content_for :custom_meta_tags do %>
  <meta name="description" content="<%= @talk.title %>" />

  <meta property="og:title" content="<%= @talk.title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="<%= @talk.poster_url %>" />

  <meta property="twitter:title" content="<%= @talk.title %>" />
  <meta property="twitter:image" content="<%= @talk.poster_url %>" />
<% end %>

<div class="container">
    <article class="talk">
        <div class="talk__video">
            <%= raw @talk.embed %>
        </div>

        <h1 class="talk__title">
            <%= @talk.title %>
        </h1>

        <div class="talk__body">
            <%= raw markdown @talk.content %>
        </div>

        <div>
            <%= render "shared/disqus" %>
        </div>

    </article>
</div>